services:
  - type: web
    name: ghibli-quizz-socket
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run start:socket
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOCKET_HOST
        value: 0.0.0.0
      - key: CLIENT_ORIGIN
        fromService:
          type: web
          name: ghibli-quizz-app
          property: host

  - type: web
    name: ghibli-quizz-app
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_PUBLIC_SOCKET_URL
        value: https://ghibli-quizz-socket.onrender.com
